version: '3'
services:
  prometheus:
    build: prometheus/.
    ports:
      - "9090:9090"

  grafana:
    build: grafana/.
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
     - .:/var/lib/grafana
    environment:
      DS_NAME: Prometheus
      DS_TYPE: Prometheus
      DS_ACCESS: direct
      DS_URL: 127.0.0.1:9090
      DS_PASS: admin
      DS_USER: admin

  alertmanager:
    build: alertmanager/.
    depends_on:
      - prometheus
    ports:
      - "9093:9093"
